project:
  type: website

website:
  title: "The Data Quest: Saumya’s Path to Discovery"

navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Saumya6915
format:
  html:
    theme: website
    css: styles.css



