project:
  type: website

website:
  title: "The Data Quest: Saumya’s Path to Discovery"

  navbar:
      background: "#023e60"
      right:
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://github.com/Saumya6915
format:
  html:
    theme: null
    css: styles.css



